# Generated by Django 4.1.7 on 2023-04-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_additionalimage_options_alter_bb_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='currency',
            field=models.CharField(blank=True, choices=[('UAH', 'UAH'), ('USD', 'USD'), ('EUR', 'EUR')], default=None, max_length=10, verbose_name='Валюта'),
        ),
    ]
