# Generated by Django 4.1.7 on 2023-04-25 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_bb_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bb',
            options={'ordering': ['-created_at'], 'verbose_name': 'Оголошення', 'verbose_name_plural': 'Оголошення'},
        ),
    ]
